### ISSUE TITLE
Adding Stage management to Runs

### ISSUE THREAD

**Issue by Annecy169** [UP929312/ado-wrapper#1]
Within ADO you have the ability to trigger a run while excluding certain stages.
<img width="538" alt="image" src="https://github.com/UP929312/ado-wrapper/assets/24814075/393bcfb1-f78f-4e33-95c0-f02395957acb">
However with this functionality in the API the listing of the stages is an unsupported API endpoint `
POST https://dev.azure.com/${ORG_NAME}/_apis/Contribution/HierarchyQuery/project/${PROJECT_ID}`
PAYLOAD:
`{"contributionIds":["ms.vss-build-web.pipeline-run-parameters-data-provider"],"dataProviderContext":{"properties":{"pipelineId":${PIPELINE_ID},"sourceBranch":"refs/heads/${BRANCH}","sourceVersion":"","onlyFetchTemplateParameters":false,"templateParameters":${TEMPLATE PARAMETER},"sourcePage":{"url":"https://dev.azure.com/${ORG_NAME}/${PROJECT_NAME}/_build?definitionId=${PIPELINE_ID}&_a=summary","routeId":"ms.vss-build-web.pipeline-details-route","routeValues":{"project":"${PROJECT_NAME}","viewname":"details","controller":"ContributedPage","action":"Execute","serviceHost":"${ORG_ID} (${ORG_NAME})"}}}}}`

Then output of this will be in `dataProviders.ms.vss-build-web.pipeline-run-parameters-data-provider.stages`.
This should then be extrapolated by an input to the function of stages to run in order to get the list of stages to skip.
Then when creating the run you need to pass in the payload of stages to skip `stagesToSkip: ["build",]`

**Comment by UP929312** [comment]
Merged via b936b20
